### ISSUE TITLE
GbxReader has issues with &amp;

### ISSUE THREAD

**Issue by w1lla** [maniaplanet/dedicated-manager#7]
Hi,

2015-02-02T19:35:29+01:00  Cannot parse `Downloaded/Trackmania_2@nadeolabs/79201.Map.Gbx`
2015-02-02T19:35:29+01:00  Cannot parse `exception 'ErrorException' with message 'simplexml_load_string(): Entity: line 1: parser error : xmlParseEntityRef: no name' in C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Utils\GbxReader\Map.php:90
Stack trace:
#0 [internal function]: ManiaLib\Application\ErrorHandling::exceptionErrorHandler(2, 'simplexml_load_...', 'C:\tmn\usbwebse...', 90, Array)
#1 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Utils\GbxReader\Map.php(90): simplexml_load_string('<header type="m...')
#2 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Utils\GbxReader\Map.php(60): DedicatedManager\Utils\GbxReader\Map::fetchChunk005(Object(DedicatedManager\Utils\GbxReader\Map), Resource id #68)
#3 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Utils\GbxReader\FileStructure.php(17): DedicatedManager\Utils\GbxReader\Map::fetch(Resource id #68)
#4 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Services\MapService.php(57): DedicatedManager\Utils\GbxReader\FileStructure::read('C:\tmn\mp3serve...')
#5 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Services\MapService.php(148): DedicatedManager\Services\MapService->get('79201.Map.Gbx', 'Downloaded/Trac...')
#6 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\libraries\DedicatedManager\Controllers\Maps.php(29): DedicatedManager\Services\MapService->getList('Downloaded/Trac...')
#7 [internal function]: DedicatedManager\Controllers\Maps->index('Downloaded/Trac...')
#8 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\vendor\maniaplanet\manialib\libraries\ManiaLib\Application\Controller.php(193): call_user_func_array(Array, Array)
#9 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\vendor\maniaplanet\manialib\libraries\ManiaLib\Application\Controller.php(92): ManiaLib\Application\Controller->executeAction('index')
#10 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\vendor\maniaplanet\manialib\libraries\ManiaLib\Application\Dispatcher.php(80): ManiaLib\Application\Controller->launch(NULL)
#11 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\vendor\maniaplanet\manialib\libraries\ManiaLib\Application\Bootstrapper.php(44): ManiaLib\Application\Dispatcher->run()
#12 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\vendor\maniaplanet\manialib\libraries\ManiaLib\Application\Bootstrapper.php(30): ManiaLib\Application\Bootstrapper::onDispatch()
#13 C:\tmn\usbwebserver\root\maniaplanet-dedicated-manager\www\index.php(8): ManiaLib\Application\Bootstrapper::run()
#14 {main}`

Is what i get as error. Map: http://tm.mania-exchange.com/tracks/view/79201 Seems to be in the zone of the player there is a Ampersand. Could this be fixed? Dedicated manager is a usefull tool with alot of additions ;)

**Comment by satanasdiabolo** [comment]
Hi,
thanks for the bug report, it's indeed because there is a non escaped "&" in the authorzone.
We will fix this.

**Comment by w1lla** [comment]
Thank you for looking in to it.

2015-02-09 15:09 GMT+01:00 satanasdiabolo notifications@github.com:
